// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonChevronLeft: typeof import('~icons/carbon/chevron-left')['default']
    Note: typeof import('./src/components/Note.vue')['default']
    Paper: typeof import('./src/components/Paper.vue')['default']
  }
}

export { }
